#python 3.7.1
i=1
while i < 10:
    poggers = "poggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggerspoggers"
    print(poggers * 99999)
i+=1
